### ISSUE TITLE
Runtime Error: add_cookies only takes a Hash or a String

### ISSUE THREAD

**Issue by jmcaffee** [jmcaffee/qbt_client#13]
TP v1.1.1-beta
qBitTorrent v3.3.13

Error:
```
	add_cookies only takes a Hash or a String

Exception type: RuntimeError
/usr/local/src/torrent_processor-1.1.1.beta/torrent_processor-1.1.1.beta.jar!/META-INF/gem.home/gems/httparty-0.14.0/lib/httparty/cookie_hash.rb:14:in `add_cookies'
/usr/local/src/torrent_processor-1.1.1.beta/torrent_processor-1.1.1.beta.jar!/META-INF/gem.home/gems/qbt_client-1.0.0/lib/qbt_client/web_ui.rb:37:in `initialize'
/usr/local/src/torrent_processor-1.1.1.beta/torrent_processor-1.1.1.beta.jar!/META-INF/app.home/lib/torrent_processor/controller.rb:125:in `init_services'
/usr/local/src/torrent_processor-1.1.1.beta/torrent_processor-1.1.1.beta.jar!/META-INF/app.home/lib/torrent_processor/controller.rb:45:in `initialize'
jar:file:/usr/local/src/torrent_processor-1.1.1.beta/torrent_processor-1.1.1.beta.jar!/META-INF/app.home/bin/torrent_processor:46:in `initialize'
jar:file:/usr/local/src/torrent_processor-1.1.1.beta/torrent_processor-1.1.1.beta.jar!/META-INF/app.home/bin/torrent_processor:152:in `<eval>'
org/jruby/RubyKernel.java:983:in `eval'
classpath:jar-bootstrap.rb:34:in `block in classpath:jar-bootstrap.rb'
org/jruby/RubyArray.java:1593:in `each'
classpath:jar-bootstrap.rb:29:in `<top>'


```

**Comment by jmcaffee** [comment]
qBitTorrent wiki [indicates](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#changes) that `API14` now requires a `Referer` header.

Lack of this header is probably causing authorization failure, so `SID` is returned as `nil` causing error above.
